### ISSUE TITLE
Make GameState extendable

### ISSUE THREAD

**Issue by nbarriga** [santiontanon/microrts#10]
I would like to be able to inherit from GameState to construct a partial view of it for use internally in my bot. Something similar to what the PartiallyObservableGameState class does. 

However, some of the internals, are package-private, rather than protected.

This means I would have to put my new class in the same package, which doesn't work if I want to keep my bot in a separate JAR. Would it be possible for you to change some attributes to protected and add a new constructor?

```  
protected PhysicalGameState pgs = null;
protected HashMap<Unit,UnitActionAssignment> unitActions = new LinkedHashMap<Unit,UnitActionAssignment>();



    protected GameState(GameState gs){
    	pgs=gs.getPhysicalGameState().cloneKeepingUnits();
    	utt=gs.getUnitTypeTable();
    	time=gs.getTime();
    	unitCancelationCounter=gs.unitCancelationCounter;
    	unitActions.putAll(gs.unitActions);
    }

```

**Comment by santiontanon** [comment]
Absolutely! done! :)
