### ISSUE TITLE
SocketAI (JSON) not sending "getAction" request.

### ISSUE THREAD

**Issue by scottazord** [santiontanon/microrts#17]
Greetings,

An action request is not being sent, I believe this is due to the action socket not being flushed.
The issue seems to be in SocketAI.java, line 158 where the out_pipe.flush() is commented out.

This should be uncommented. 

Regards,
Scott.

**Comment by santiontanon** [comment]
Ok, I'll check this out, probably you are right!!!

**Comment by santiontanon** [comment]
I just committed a fix. Uncommenting that line you mentioned, and also I added more debugging messages in the SocketAI (that can be turned on by setting SocketAI.DEBUG = 1) in case this still happens, to help me narrow down the issue.

Let me know if it works now, and thanks for reporting :)

**Comment by scottazord** [comment]
Thanks Santiontanon,

It works out of the box now.  :100:

**Comment by santiontanon** [comment]
Awesome! Thanks for reporting! :)
