### ISSUE TITLE
Duplicated ID in map

### ISSUE THREAD

**Issue by axgdev** [santiontanon/microrts#24]
Hi,

I discovered this by mistake. Suppose you have this simple map:

```
<rts.PhysicalGameState width="2" height="2">
  <terrain>0000</terrain>
  <players>
    <rts.Player ID="0" resources="0">
    </rts.Player>
    <rts.Player ID="1" resources="0">
    </rts.Player>
  </players>
  <units>
    <rts.units.Unit type="Base" ID="5" player="0" x="1" y="1" resources="0" hitpoints="10" >
    </rts.units.Unit>
    <rts.units.Unit type="Worker" ID="5" player="1" x="0" y="1" resources="0" hitpoints="1" >
    </rts.units.Unit>
  </units>
</rts.PhysicalGameState>
```

I defined by mistake the BaseID and the WorkerID to be the same and the game loaded it without problem. Then I tried to retrieve a unit by ID and I would get the unit I did not want. 

I think the ID of the units should be unique, right? Maybe it would be good to check that a unit is never assigned the ID of another unit. Perhaps it is only the case when the map is loading.

**Comment by santiontanon** [comment]
Correct! this should never happen, and indeed I think we should have a check when map is loading to prevent this. Added to my to-do list, will let you know when it's in place. Thanks for noticing! :)

**Comment by santiontanon** [comment]
actually, it was just a 1 line change, so I just committed a fix for this. Loading a map with this problem will now throw an exception :)

**Comment by axgdev** [comment]
Wow, that was quick! Thanks!
