### ISSUE TITLE
About the Bayesian method

### ISSUE THREAD

**Issue by CHINAEEB** [santiontanon/microrts#32]
Hello 

Thank you very much for your contribution to our research on real-time strategy games. How can I use the Bayesian method in the package? Is there a related introduction document?

From a graduating postgraduate student for help.

**Comment by santiontanon** [comment]
Hi! 

Unfortunately there is no more documentation than the code itself, and this paper, where the methods are described: https://www.researchgate.net/profile/Santiago_Ontanon2/publication/313952380_Informed_Monte_Carlo_Tree_Search_for_Real-Time_Strategy_games/links/5afe29ff458515e9a5763d99/Informed-Monte-Carlo-Tree-Search-for-Real-Time-Strategy-games.pdf <https://www.researchgate.net/profile/Santiago_Ontanon2/publication/313952380_Informed_Monte_Carlo_Tree_Search_for_Real-Time_Strategy_games/links/5afe29ff458515e9a5763d99/Informed-Monte-Carlo-Tree-Search-for-Real-Time-Strategy-games.pdf>

But basically, you just need a training set of replays to train your model, and then you can use it as the model for a “UnitActionProbabilityDistributionAI”, which you can use as any other AI

santi

**Comment by CHINAEEB** [comment]
Thank you very much for your reply. I will continue to study, thank you again！！！

**Comment by CHINAEEB** [comment]
I have carefully studied your article”Informed Monte Carlo Tree Search for Real-Time Strategy Games”.Thank you for your research in real-time strategy games, which gives us a lot of research methods. In article,you evaluated the probability distribution models in two different ways. I am very anxious to know how the “Model Play Strength” method is implemented in the “microrts-master” code.Sincerely look forward to your reply.







On 10/9/2018 11:52，Santi Ontañón Villar<notifications@github.com> wrote：
Hi!

Unfortunately there is no more documentation than the code itself, and this paper, where the methods are described: https://www.researchgate.net/profile/Santiago_Ontanon2/publication/313952380_Informed_Monte_Carlo_Tree_Search_for_Real-Time_Strategy_games/links/5afe29ff458515e9a5763d99/Informed-Monte-Carlo-Tree-Search-for-Real-Time-Strategy-games.pdf <https://www.researchgate.net/profile/Santiago_Ontanon2/publication/313952380_Informed_Monte_Carlo_Tree_Search_for_Real-Time_Strategy_games/links/5afe29ff458515e9a5763d99/Informed-Monte-Carlo-Tree-Search-for-Real-Time-Strategy-games.pdf>

But basically, you just need a training set of replays to train your model, and then you can use it as the model for a “UnitActionProbabilityDistributionAI”, which you can use as any other AI

santi

**Comment by santiontanon** [comment]
Sure! I can explain that!

The way to do it is as follows:
1) The first thing is to generate replays. There is a class called "GenerateTrainingTraces.java" that has a version of the code I used for that paper.
2) Then you need to train a model. For example, the AIM model corresponds to the class ActionInterdependenceModel.java, and the CNB model is the class CalibratedNaiveBayes.java. The class PretrainNaiveBayesModels.java has examples of how to do this.
3) Finally, once you have your model trained (notice you can save it to disk after it's trained, so, you don't need to train it again), you can create an AI to play the game with the UnitActionProbabilityDistributionAI.java class, which encapsulates an AI that uses your trained model to play the game.
4) Then you can just use it to play, for example using the GameVisualSimulationTest.java, for example

I hope this helps!

**Comment by santiontanon** [comment]
Awesome! Glad to hear it, I'll close this issue then! Looking forward to your results! :)
