### ISSUE TITLE
Stuck when running tournaments in mac X OS 10.14.3

### ISSUE THREAD

**Issue by jsyx1994** [santiontanon/microrts#34]
Hi!
I want to run one tournaments with the microRTS gui, but it stuck and did not write anything into my disk(only a zero size csv file). I also tested on windows 10 64bit, it works will.

**Comment by santiontanon** [comment]
Hi, can you give me more details about the situation? which bots were used, which tournament type, which maps, parameters, etc.?

I run everything form Mac OS and Linux computers and haven’t experienced that problem.

santi

**Comment by jsyx1994** [comment]
Hi, thanks for your reply. 
The picture I sent shows the details, and … Regardless of which bots I use and the tournaments and maps I choose, it always stucks.  
Moreover, I use the latest java version(1.8.0_201) and netbeans 10(also intelliJ Idea). It just cannot run on Mac but can do well on win10. 
![image](https://user-images.githubusercontent.com/18167093/53137384-8b14d480-35bd-11e9-9b3d-d6a12b55aef5.png)

**Comment by santiontanon** [comment]
Hmm, I just tried it on Mac with Java 10.0.1, and Netbeans 10 and it worked fine

Does it write anything on the text box at the bottom of the pane? or does it create the tournament data folder (e.g. “tournament_1/“) and the tournament data file (e.g., “tournament_1/tournament.csv”)? If it does, can you see what is the last thing that is written? Another thing that could happen is file permissions. The first thing that the tournament code tries to do is to create a new folder. If it does not have write permissions in Mac/Linux, it might just block there. Do you think this is the problem? Also, which working directory are you running it from? make sure it’s the root folder of microRTS

santi

**Comment by jsyx1994** [comment]
Emmm... I cloned the microRTS again and used netbeans to create the project again, finally it worked. I appreciate it very much for your help. : )

**Comment by santiontanon** [comment]
Good! glad it worked! :)
