### ISSUE TITLE
2017 Competition Replays Lost

### ISSUE THREAD

**Issue by Vigilans** [santiontanon/microrts#37]
The replays for competitions in 2017 cited below had gone away...which I'd like to use as dataset for reinforcement learning methods.
https://www.dropbox.com/s/nrvglg0cj4c5fw0/microRTS-CIG2017-competition-replays.zip?dl=0

Apart from aforementioned replays, is there any other dataset available?

**Comment by santiontanon** [comment]
Oh, you are right! DropBox changed the public folder policy about a year ago, and I didn't realize that that broke the download link. I am happy to share the replays from the 2017 and/or the 2018 competitions. Just send me an email from the email account you want me to share the files with you (I will send you an invite to the files from DropBox), and I'll send them to you right away! :)

**Comment by Vigilans** [comment]
Thanks!
