### ISSUE TITLE
The equivalents method in PhysicalGameState does not compare terrains

### ISSUE THREAD

**Issue by Acemad** [santiontanon/microrts#43]
The `equivalents(pgs)` method in the `PhysiscalGameState `class is supposed to compare two physical game states and return `true` if both of them are identical. This method successfully compares : 

- The pgs's width and height
- Players (count, IDs and resources) 
- Units (count, type, hit points and x,y coordinates)

But what if the terrain is different ? equivalents will return `true` if all parameters are equal but terrains are different.

1. Is this a desired behavior ?
2. If it is not, I suggest adding a terrain comparison to `equivalents` by comparing a `String` representation of both terrains, or using `Arrays.deepEquals`

**Comment by Acemad** [comment]
I think this is a desired behavior, since most of the time comparison is done in the same map, where terrain does not change. But won't there be a situation where a terrain comparison is needed ?

**Comment by santiontanon** [comment]
Hi Acemad, I thought about this when implementing the comparison function, and decided not to compare terrains, as there is no way in the current implementation of the game where the terrain can change. So, unless you are comparing PhysicalGameStates from different maps, there is no need. Maybe we could have a separate function "equivalentsIncludingTerrain" or something like that that compares the terrain, in case it is useful for agents that do some sort of learning across different maps and need this comparison?

**Comment by Acemad** [comment]
Hello, thanks for the swift response.
Yes, I realized that a bit late. Thanks for the clarification.
For the sake of future proofing, I think I will implement `equivalentsIncludingTerrain` , because, as you stated, there can be some use of full physical state (including terrain) comparison in the future. 
Should I do it ?

**Comment by santiontanon** [comment]
Sure thing! you can send a pull request, and I'd be more than happy to accept it! :)

Thanks a lot for the contribution if you end up doing it! :)

**Comment by Acemad** [comment]
PR #44 sent !
Thanks you very much, I'm really glad to help out :D

**Comment by santiontanon** [comment]
Thanks for the PR! Will close this issue then! :)
