### ISSUE TITLE
Few issues in getPlayerActionsSingleUnit

### ISSUE THREAD

**Issue by Acemad** [santiontanon/microrts#45]
The `getPlayerActionsSingleUnit` method in the `GameState` class, from what I understood, returns a `List<PlayerAction>` list containing `UnitAction`s for the provided `Unit`, that are consistent with the `UnitAction`s in `unitActions` map. The `PlayerAction`s returned only contain a single `UnitAction`, but also include the full `ResourceUsage` of `unitActions`.

I have identified two slightly confusing issues that can be misleading : 
1. The method expects two arguments, a `pID` and a unit. But, the `pID` is not needed anymore, but it's still present. There are only two usages of this method in the codebase, specifically in `UCTUnitActionsNode`, where it is used for maxplayer and minplayer, whereas, this differentiation doesn't hold much meaning and can be trivially fixed by eliminating the superfluous argument.
2. A superfluous for loop (2nd one) that loops through a list with a single element that never changes prior to the start of this loop.
    ```java
    for(PlayerAction pa:l) { // l has only one element, all the time
        l2.addAll(pa.cartesianProduct(unit.getUnitActions(this), unit, this));
    }
    ```

Before fixing those issues, I would like to confirm the correctness of such reasoning.

**Comment by santiontanon** [comment]
Hi Acemad, I think you are correct in all respects. The "pID" argument can indeed be removed, as it is a leftover of a previous version of this function that only returned the resources used by a single player. This had some issues, and thus I changed it to return the resources used by all units, but never removed the parameter. As for the superfluous loop, indeed it can be replaced by a single call to cartesianProduct.

**Comment by Acemad** [comment]
Hello Mr. Ontanon, and thank you very much for reviewing and merging the last PR, and for confirming the small issues presented here. I will fix them quickly and issue a new PR :)

**Comment by Acemad** [comment]
PR #46 sent. I've also removed the l2 list and replaced all the code inside the conditional statement by a single call to cartesianProduct.
