### ISSUE TITLE
PhysicalGameStateTest.java depends on junit, which is not included in lib

### ISSUE THREAD

**Issue by douglasrizzo** [santiontanon/microrts#50]
I noticed that [tests.rts.PhysicalGameStateTest](https://github.com/santiontanon/microrts/blob/a616a0b91de25fdf5a2724d2fdcc020e906496f1/src/tests/rts/PhysicalGameStateTest.java) depends on junit, which is not included in microRTS. For some reason, when I try to build the project on Intellij, I get an error because of that. I used [this JAR](https://search.maven.org/artifact/junit/junit/4.13-rc-1/jar) to fix the problem.

I don't know if junit should be added to lib or if `PhysicalGameStateTest.java` should be made to not depend on junit. Since this is the only test class that uses junit, I believe the dependency was never intended to exist.

**Comment by santiontanon** [comment]
Oh! never even realized that file was there. I guess it sneaked in with some pull request I accepted without looking at it carefully! I would prefer to remove the dependency from JUnit since, as you say, it is the only one test there! I'll fix it asap

**Comment by santiontanon** [comment]
Fixed :)
