### ISSUE TITLE
Compress terrain String representation for socket message

### ISSUE THREAD

**Issue by douglasrizzo** [santiontanon/microrts#57]
Hi there @santiontanon. Thanks for being so receptive of my contributions. I am trying to apply what I have learned from previous projects into microRTS in hopes to make it better for me and future users and I am really glad you are open to contributions to the project.

Anyway, when I was looking at the JSON representation of a state, I realized that the terrain information is a binary string (composed only of 0s and 1s) which is passed as a large String of size `width * height`. So, not only are its contents very simple, but it grows quadratically with the size of the map.

I decided to test a simple method to compress a String with those properties. I count the number of consecutive occurrences of a character and append this counter to a String, along with the character itself. Since 0 and 1 may appear inside the counter, 0 is replaced by A and 1 is replaced by B. For example, the string `00000011110000000000` is transformed into `A6B4A10`.

I think this is especially beneficial, since many maps only have terrains and no walls, so they are fully composed of 0s.

I created functions to make this compression and decompression [inside the `PhysicalGameState` class](https://github.com/douglasrizzo/microrts/blob/a46f03981313f1531475ec026fea568a80b6f8b6/src/rts/PhysicalGameState.java#L499-L579). I made sure they are reversible (`t == uncompressTerrain(compressTerrain(t))`).

I also implemented the decompression function [in Python](https://github.com/douglasrizzo/python-microRTS/blob/8b41bce4c82b81bb5ef208bba68e95c9282e4b4e/pyrts/server.py#L91-L109) and made a successful client-server communication test.

Lastly, I compared two text files with 720 states (saved as JSON) and saw a decrease of 15% in the size of the file that used compressed terrain representations.

```json
{"time":0,"pgs":{"width":16,"height":16,"terrain":"0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000","players":[{"ID":0, "resources":5},{"ID":1, "resources":5}],"units":[{"type":"Resource", "ID":16, "player":-1, "x":0, "y":0, "resources":25, "hitpoints":1},{"type":"Resource", "ID":17, "player":-1, "x":0, "y":1, "resources":25, "hitpoints":1},{"type":"Resource", "ID":18, "player":-1, "x":15, "y":14, "resources":25, "hitpoints":1},{"type":"Resource", "ID":19, "player":-1, "x":15, "y":15, "resources":25, "hitpoints":1},{"type":"Base", "ID":20, "player":0, "x":2, "y":2, "resources":0, "hitpoints":10},{"type":"Base", "ID":21, "player":1, "x":13, "y":13, "resources":0, "hitpoints":10},{"type":"Worker", "ID":22, "player":0, "x":1, "y":1, "resources":0, "hitpoints":1},{"type":"Worker", "ID":23, "player":1, "x":14, "y":14, "resources":0, "hitpoints":1}]},"actions":[]}
{"time":0,"pgs":{"width":16,"height":16,"terrain":"A256","players":[{"ID":0, "resources":5},{"ID":1, "resources":5}],"units":[{"type":"Resource", "ID":16, "player":-1, "x":0, "y":0, "resources":25, "hitpoints":1},{"type":"Resource", "ID":17, "player":-1, "x":0, "y":1, "resources":25, "hitpoints":1},{"type":"Resource", "ID":18, "player":-1, "x":15, "y":14, "resources":25, "hitpoints":1},{"type":"Resource", "ID":19, "player":-1, "x":15, "y":15, "resources":25, "hitpoints":1},{"type":"Base", "ID":20, "player":0, "x":2, "y":2, "resources":0, "hitpoints":10},{"type":"Base", "ID":21, "player":1, "x":13, "y":13, "resources":0, "hitpoints":10},{"type":"Worker", "ID":22, "player":0, "x":1, "y":1, "resources":0, "hitpoints":1},{"type":"Worker", "ID":23, "player":1, "x":14, "y":14, "resources":0, "hitpoints":1}]},"actions":[]}
```

I also changed the methods that read XML and JSON to automatically detect if the terrain data is compressed and decompress it as needed.

If you find this interesting, I could create a pull request with this contribution.
I was thinking about adding a property to the `config.properties` so users can choose whether they want their client/server communication to employ this compression method or not.

**Comment by douglasrizzo** [comment]
Actually, an additional question. Is there a reason to send the terrain data in every state? Does it change during the game? Can't it be included in the header?

**Comment by santiontanon** [comment]
Interesting. So, basically you are doing "run length encoding", which
should be fairly efficient in this type of data! I'll review this pull
request tonight after work! As for your question, good point. No, the
terrain can never change, so, you are right that there is no point in
sending it again and again every frame.

**Comment by douglasrizzo** [comment]
So we can work on sending the terrain along with the header (with `budget` and `utt`). Using run-length encoding may not be necessary or become something optional.

**Comment by santiontanon** [comment]
Yep, sounds like a good idea. I wonder if there is anyway to do this without breaking compatibility, as there are a few AIs submitted to the microRTS competitions that rely on this interface. So, maybe we can extend the existing class, so that the old one remains in the code for compatibility purposes. And in the new one, maybe we can include a "version ID" in the early handshaking, so that future extensions do not require creating new classes.

**Comment by douglasrizzo** [comment]
I just realized there is a pre-game analysis method which allows agents to do some pre-processing in an initial state.

I believe it's a good idea to send this first state in the pre-game analysis phase with the terrain information and subsequent states would not need to have this information anymore. The same applies to the map height and width.

I already have something of the sorts working. I am trying to not break compatibility with the existing code.
