### ISSUE TITLE
Introduce features from new Java versions into the code base

### ISSUE THREAD

**Issue by douglasrizzo** [santiontanon/microrts#59]
**Java 5** introduced the "foreach" loops, which can replace 28 traditional for loops in microRTS.

**Java 7** introduced the diamond operator, which simplifies how objects that take Generics as arguments are instantiated. For example

```java
ArrayList<Integer> l = new ArrayList<Integer>();
```

can now be created like this:
```java
ArrayList<Integer> l = new ArrayList<>();
```

There are 274 places where this change can be made in microRTS.

Lastly, **Java 8** introduced lambda expressions, which can replace anonymous types 77 times in the code base. An example of that is
```java
Collections.sort(featureIndexes, new Comparator<Integer>() {
    public int compare(Integer o1, Integer o2) {
        return Double.compare(featureGR.get(o2), featureGR.get(o1));
    }            
});
```

which can be simplified to
```java
Collections.sort(featureIndexes, (o1, o2) -> Double.compare(featureGR.get(o2), featureGR.get(o1)));
```

The automated tests of microRTS made me realize that the repository already is compatible only with Java 8/9 upwards, so these changes would not break compatibility. Would changes like these be interesting in the master repo of microRTS?

**Comment by santiontanon** [comment]
Good point! The project started as Java 6, and the files that I was working on got turned into Java 7, and some into Java 8. But never did a complete revision of the code. I would say that the "foreach" and the "diamonds" should definitively be done!

I am not sure yet about the lambda expressions, as I have not yet studied how do they work. So, I'd prefer is we hold on on that last change. But yes, the other two would be very welcome!

**Comment by santiontanon** [comment]
I am going to close this issue, as we already merged your pull request on this ;)
