### ISSUE TITLE
support Python 

### ISSUE THREAD

**Issue by nanxintin** [santiontanon/microrts#8]
Hi ,
Do you have any plan for supporting python? I think that will be much easy for AI research with machine learning approach, especially deep learning.
Thanks.

**Comment by santiontanon** [comment]
Hi! This is something that I definitively want to add. I'm still looking to see what is the better way to make Java and Python communicate though. But I'll update you of any progress in this direction in this thread!

**Comment by andertavares** [comment]
The platform of Fighting Game Competition (http://www.ice.ci.ritsumei.ac.jp/~ftgaic/) is in Java and they provided Python support via Py4J. Maybe something can be done in this sense for microRTS as well...

**Comment by santiontanon** [comment]
I asked my local Python guru about that a few weeks ago, and he said that Py4J is a bit limited though. But if that is something that people would use, I can sure work toward adding it.

**Comment by andertavares** [comment]
I see. Maybe a good way to go is to write a socket-based protocol to read information and send commands from/to microRTS, so that anyone could use their language of choice. This could be a lot of work, though...

**Comment by santiontanon** [comment]
I think this is the way to go. I'll add it to my to-do list to play around! I have wanted to add this for a long time, so, now that there is an official "issue" open in the repository, I cannot procrastinate anymore, and I should add it! :)

**Comment by santiontanon** [comment]
Ok, this is finally implemented! There is now a class called "SocketAI", which communicates with an external AI via sockets. Communication language can be either XML or JSON for now (other options could be added if needed). A quick explanation of how this works can be seen at the bottom of this page: https://github.com/santiontanon/microrts/wiki/Code-Guide

And an example can be seen in the "test/sockets" package. In the example, the AI that communicates via Socket is built in Java, but it could perfectly be Python or any other language :)

I am going to close the ticket, but if you think some more features would be useful along these lines, please feel free to reopen! :)

**Comment by santiontanon** [comment]
oh wow!! This is amazing, thanks a lot! I'll distribute among my students,
who will definitively find it useful!
