### ISSUE TITLE
Instructions on creating JAR file

### ISSUE THREAD

**Issue by douglasrizzo** [santiontanon/microrts#81]
Hi there @santiontanon, happy new year.

Recently, I found myself in need of creating a single microRTS JAR file, so that I could autonomously start microRTS from another script without the need of configuring classpaths. I learned how to do it via the command-line and added it to [the README in my fork](https://github.com/douglasrizzo/microrts/blob/default-values/README.md#generating-a-jar-file).

Maybe if I polish the instructions a little more, would that be an acceptable contribution for the upstream repo?

I also thought about gathering these compilation and execution instructions into a wiki page instead of keeping them in the README. What do you think?

**Comment by santiontanon** [comment]
Hi Douglas, happy new year!

I think both are great ideas, adding it to the readme as you have it in
yours, and then having a wiki page with a bit more info (for now it can be
the same, and I can grow it from there!), linked from the read me, would be
perfect!
